name: Build Android

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Criar Gradle Wrapper
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: '8.13'

      - name: Compilar APK
        run: gradle assembleDebug
